<?php

namespace RenokiCo\EchoServer;

use Pusher\Pusher;

class EchoPusher extends Pusher
{
    /**
     * {@inheritdoc}
     */
    private function validate_socket_id($socket_id)
    {
        // Do not validate Socket IDs because they are
        // generated by Socket.IO
    }
}
